apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stock-controller
spec:
  template:
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/stock-controller:v1
        imagePullPolicy: Always